parser: babel-eslint
env:
  browser: true
  es2021: true
  jest: true
  jest/globals: true
extends:
  - airbnb-base
plugins:
  - jest
parserOptions:
  ecmaVersion: 12
  sourceType: module
rules: {
   no-unused-expressions: 0
}
